# Generated by Django 3.2.5 on 2021-07-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poemid', models.IntegerField()),
                ('poemen', models.TextField()),
                ('poemcn', models.TextField()),
            ],
        ),
    ]
